#!/usr/bin/env bash
# End-to-end test of linux/Medicat_Installer.sh --install on a loop device: Ventoy install, NTFS
# format, mount, extract, MD5 verify. Writes only to a sparse image in a temporary directory and
# to the loop device created from it. Needs root (losetup, Ventoy2Disk.sh, mkntfs, mount), 7z,
# and network for the Ventoy download unless MEDICAT_TEST_VENTOY_TAR names a local
# ventoy-X.Y.Z-linux.tar.gz. Run from the repository root:
#   sudo bash tests/linux/loop_install_test.sh
set -u

if (( EUID != 0 )); then
	echo "FAIL: run as root (sudo bash $0)"
	exit 1
fi

repoRoot=$(cd "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
script="$repoRoot/linux/Medicat_Installer.sh"
work=$(mktemp -d "${TMPDIR:-/var/tmp}/medicat-loop.XXXXXX")
loop=""
fail=0

# shellcheck disable=SC2329  # invoked through the EXIT trap
cleanup() {
	umount "$work/mnt" 2>/dev/null || true
	umount "$work/wd/MedicatUSB" 2>/dev/null || true
	if [[ -n "$loop" ]]; then
		losetup -d "$loop" 2>/dev/null || true
	fi
	rm -rf "$work"
}
trap cleanup EXIT

check() {
	if [[ "$1" == "$2" ]]; then
		echo "PASS: $3"
	else
		echo "FAIL: $3 (got '$1', want '$2')"
		fail=1
	fi
}

md5of() {
	md5sum "$1" | awk '{print $1}'
}

# Same fixture as smoke_test.sh: a tiny tree, its QuickSFV manifest and a 7z archive of it.
fixture="$work/fixture"
mkdir -p "$fixture/sub" "$fixture/ventoy" "$work/wd" "$work/mnt"
printf 'hello\n' > "$fixture/a.txt"
printf 'world\n' > "$fixture/sub/b file.txt"
printf '{}\n' > "$fixture/ventoy/ventoy.json"
{
	printf '; Generated by QuickSFV v2.35 on 2022-01-13 at 06:29:45\r\n'
	printf '%s *a.txt\r\n' "$(md5of "$fixture/a.txt")"
	printf '%s *sub\\b file.txt\r\n' "$(md5of "$fixture/sub/b file.txt")"
	printf '%s *ventoy\\ventoy.json\r\n' "$(md5of "$fixture/ventoy/ventoy.json")"
} > "$work/fixture.md5"
(cd "$fixture" && 7z a -bso0 -bsp0 "$work/fixture.7z" . >/dev/null) || { echo "FAIL: could not create fixture.7z (7z missing?)"; exit 1; }

# 32 GiB sparse image: above the installer's 28 GiB minimum, costs only what Ventoy and mkntfs write.
truncate -s 32G "$work/disk.img"
loop=$(losetup --find --show --partscan "$work/disk.img") || { echo "FAIL: losetup failed"; exit 1; }
echo "Loop device: $loop"

args=(--install --drive "$loop" --yes --allow-fixed --archive "$work/fixture.7z" --skip-archive-hash
	--manifest "$work/fixture.md5" --extras none --work-dir "$work/wd")
if [[ -n "${MEDICAT_TEST_VENTOY_TAR:-}" ]]; then
	args+=(--ventoy-tar "$MEDICAT_TEST_VENTOY_TAR")
fi
bash "$script" "${args[@]}" > "$work/install.txt" 2>&1
code=$?
if (( code != 0 )); then
	sed -E $'s/\e\\[[0-9;]*[A-Za-z]//g' "$work/install.txt" | tail -n 40
fi
check "$code" "0" "--install on the loop device exits 0"
udevadm settle 2>/dev/null || true

check "$(blkid -p -o value -s TYPE "${loop}p1")" "ntfs" "data partition is NTFS"
check "$(blkid -p -o value -s LABEL "${loop}p1")" "Medicat" "data partition label is Medicat"
check "$(blkid -p -o value -s LABEL "${loop}p2")" "VTOYEFI" "Ventoy EFI partition exists"
grep -q "All 3 files verified OK" "$work/install.txt"; check "$?" "0" "installer verified the extracted files"
! mountpoint -q "$work/wd/MedicatUSB"; check "$?" "0" "installer unmounted its MedicatUSB mountpoint"

mount -o ro "${loop}p1" "$work/mnt" 2>/dev/null; check "$?" "0" "data partition mounts read-only"
check "$(cat "$work/mnt/a.txt" 2>/dev/null)" "hello" "extracted file matches the fixture"
[[ -f "$work/mnt/sub/b file.txt" && -f "$work/mnt/ventoy/ventoy.json" ]]; check "$?" "0" "nested files were extracted"
[[ ! -e "$work/mnt/failed_files.txt" ]]; check "$?" "0" "no failed_files.txt on the stick"

exit $fail
