#!/usr/bin/env bash
# Smoke tests for linux/Medicat_Installer.sh that need no USB stick and no root:
# argument handling, --verify/--repair against a tiny fixture, and (optionally) one small
# extras download. Run from the repository root, or via CI. Set MEDICAT_TEST_NETWORK=0 to
# skip the download test.
set -u

repoRoot=$(cd "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
script="$repoRoot/linux/Medicat_Installer.sh"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
fixture="$work/fixture"
wd="$work/wd"
fail=0

check() {
	if [[ "$1" == "$2" ]]; then
		echo "PASS: $3"
	else
		echo "FAIL: $3 (got '$1', want '$2')"
		fail=1
	fi
}

md5of() {
	md5sum "$1" | awk '{print $1}'
}

# Fixture: three files, a QuickSFV-style manifest with backslash paths and CRLF, and a 7z
# archive of the good tree. Then corrupt one file and delete another.
mkdir -p "$fixture/sub" "$fixture/ventoy" "$wd"
printf 'hello\n' > "$fixture/a.txt"
printf 'world\n' > "$fixture/sub/b file.txt"
printf '{}\n' > "$fixture/ventoy/ventoy.json"
{
	printf '; Generated by QuickSFV v2.35 on 2022-01-13 at 06:29:45\r\n;\r\n'
	printf '%s *a.txt\r\n' "$(md5of "$fixture/a.txt")"
	printf '%s *sub\\b file.txt\r\n' "$(md5of "$fixture/sub/b file.txt")"
	printf '%s *ventoy\\ventoy.json\r\n' "$(md5of "$fixture/ventoy/ventoy.json")"
} > "$work/fixture.md5"
(cd "$fixture" && 7z a -bso0 -bsp0 "$work/fixture.7z" . >/dev/null) || { echo "FAIL: could not create fixture.7z (7z missing?)"; exit 1; }
printf 'corrupted\n' > "$fixture/a.txt"
rm "$fixture/sub/b file.txt"

bash "$script" --help > "$work/help.txt" 2>&1; check "$?" "0" "--help exits 0"
grep -q -- "--list-extras" "$work/help.txt"; check "$?" "0" "--help mentions --list-extras"
bash "$script" --version > /dev/null; check "$?" "0" "--version exits 0"
bash "$script" --list-extras > "$work/list.txt" 2>&1; check "$?" "0" "--list-extras exits 0"
grep -q "^systemrescue " "$work/list.txt"; check "$?" "0" "--list-extras prints the catalog"
bash "$script" --dump-spec > "$work/spec.txt" 2>&1; check "$?" "0" "--dump-spec exits 0"
grep -q "^Medicat7zFile=" "$work/spec.txt"; check "$?" "0" "--dump-spec prints spec values"
bash "$script" --bogus > /dev/null 2>&1; check "$?" "2" "unknown flag exits 2"
bash "$script" --extras nope --path "$fixture" > /dev/null 2>&1; check "$?" "2" "unknown extras id exits 2"
bash "$script" --install --path "$fixture" > /dev/null 2>&1; check "$?" "2" "--path with --install exits 2"
bash "$script" --download torrent --offline > /dev/null 2>&1; check "$?" "2" "--offline with --download exits 2"
bash "$script" --ventoy-version 1.2 > /dev/null 2>&1; check "$?" "2" "malformed --ventoy-version exits 2"

bash "$script" --verify --path "$fixture" --manifest "$work/fixture.md5" --yes --work-dir "$wd" --no-reextract \
	> "$work/verify1.txt" 2>&1
check "$?" "5" "verify reports failures with exit 5"
check "$(sort "$fixture/failed_files.txt" | tr '\n' '|')" "a.txt|sub/b file.txt|" "failed_files.txt lists both paths"

bash "$script" --verify --path "$fixture" --manifest "$work/fixture.md5" --yes --work-dir "$wd" --archive "$work/fixture.7z" \
	> "$work/verify2.txt" 2>&1
check "$?" "0" "verify repairs from the archive and exits 0"
check "$(cat "$fixture/a.txt")" "hello" "corrupted file restored"
[[ -f "$fixture/sub/b file.txt" ]]; check "$?" "0" "missing file restored"
[[ ! -e "$fixture/failed_files.txt" ]]; check "$?" "0" "failed_files.txt removed after repair"

bash "$script" --verify --path "$fixture" --manifest "$work/fixture.md5" --yes --work-dir "$wd" --offline > /dev/null 2>&1
check "$?" "0" "clean verify with --offline exits 0"
grep -q "verify" "$wd/medicat_installer.log"; check "$?" "0" "session log written"

if [[ "${MEDICAT_TEST_NETWORK:-1}" == "1" ]]; then
	bash "$script" --extras memtest86plus --path "$fixture" --yes --work-dir "$wd" > "$work/extras.txt" 2>&1
	check "$?" "0" "extras download exits 0"
	[[ -s "$fixture/Extras/Diagnostics/mt86plus_8.10_x86_64.iso" ]]; check "$?" "0" "memtest iso unpacked into Extras/Diagnostics"
	grep -q "^memtest86plus" "$fixture/Extras/extras_manifest.txt"; check "$?" "0" "extras_manifest.txt records the download"
	bash "$script" --extras memtest86plus --path "$fixture" --yes --work-dir "$wd" > "$work/extras2.txt" 2>&1
	check "$?" "0" "extras rerun exits 0"
	grep -q "already present" "$work/extras2.txt"; check "$?" "0" "extras rerun skips the existing image"
fi

exit $fail
