#!/usr/bin/env python3
"""Write build_number.txt and generated/build_version.cpp.

`--keep` (the default) reuses the local counter; CMake runs it before every build.
`--bump` adds one to the counter (rebuild.bat). `--set` and MEDICAT_PIN_BUILD pin a
version 1.0.N (CI pins 1.0.1). The version goes into the exe's VERSIONINFO and /version.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


def write_build_version(output: Path, major: int, minor: int, build: int) -> str:
    version = f"{major}.{minor}.{build}"
    text = f"""// Generated by tools/bump_build_number.py - do not edit.

namespace medicat {{

extern const char kInstallerVersion[] = "{version}";
extern const int kInstallerBuildNumber = {build};

}}  // namespace medicat
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    return version


def write_counter(counter_path: Path, major: int, minor: int, build: int) -> str:
    version = f"{major}.{minor}.{build}"
    counter_path.parent.mkdir(parents=True, exist_ok=True)
    counter_path.write_text(f"{version}\n", encoding="utf-8", newline="\n")
    return version


def parse_version_text(text: str, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    cleaned = text.strip()
    if not cleaned:
        return None
    if cleaned[:1] in ("v", "V"):
        cleaned = cleaned[1:]
    match = _VERSION_RE.match(cleaned)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3))
    if cleaned.isdigit():
        return default_major, default_minor, int(cleaned)
    return None


def read_counter(counter_path: Path, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    if not counter_path.exists():
        return None
    return parse_version_text(counter_path.read_text(encoding="utf-8"), default_major, default_minor)


def parse_set_value(value: str, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    parsed = parse_version_text(value, default_major, default_minor)
    if parsed is None or parsed[2] <= 0:
        return None
    return parsed


def write_both(counter: Path, output: Path, major: int, minor: int, build: int) -> str:
    version = write_counter(counter, major, minor, build)
    write_build_version(output, major, minor, build)
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description="Write installer build number")
    parser.add_argument("counter", type=Path, help="Path to version counter file (e.g. 1.0.19)")
    parser.add_argument("output", type=Path, help="Path to generated build_version.cpp")
    parser.add_argument("--major", default="1")
    parser.add_argument("--minor", default="0")
    parser.add_argument("--keep", action="store_true", help="Reuse build_number.txt unchanged (default)")
    parser.add_argument("--bump", action="store_true", help="Add one to the local build number")
    parser.add_argument("--skip-if-env", default="", help="Only regenerate the output when this variable is set")
    parser.add_argument("--set", default="", help="Force version 1.0.N (or patch N)")
    args = parser.parse_args()

    try:
        default_major = int(args.major)
        default_minor = int(args.minor)
    except ValueError:
        print(f"Invalid --major/--minor: {args.major}.{args.minor}", file=sys.stderr)
        return 1

    pin = os.environ.get("MEDICAT_PIN_BUILD", "").strip() or args.set.strip()
    if pin:
        pinned = parse_set_value(pin, default_major, default_minor)
        if pinned is None:
            print(f"Invalid pinned version: {pin}", file=sys.stderr)
            return 1
        print(f"Build number pinned: {write_both(args.counter, args.output, *pinned)}")
        return 0

    parsed = read_counter(args.counter, default_major, default_minor)

    if args.skip_if_env and os.environ.get(args.skip_if_env):
        if parsed is not None:
            major, minor, build = parsed
            print(f"Build number bump skipped ({args.skip_if_env}); using "
                  f"{write_build_version(args.output, major, minor, build)}")
        return 0

    if args.bump:
        major, minor, build = parsed if parsed is not None else (default_major, default_minor, 0)
        print(f"Build number: {write_both(args.counter, args.output, major, minor, build + 1)}")
        return 0

    if parsed is None:
        print(f"No local build_number.txt; using {write_both(args.counter, args.output, 0, 0, 0)} "
              "(rebuild.bat as 1.0.N to pin)")
        return 0
    print(f"Build number: {write_both(args.counter, args.output, *parsed)} (local, unchanged)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
