#!/usr/bin/env python3
"""Generate the shared-spec artifacts from spec/medicat.json and spec/extras.json.

Outputs (both committed, regenerated by CI and the CMake build):
  src/spec_generated.h            constants for the C++ Windows installer
  linux/Medicat_Installer.sh      the block between the GENERATED SPEC markers

Run with --check to fail when either output is stale.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "spec" / "medicat.json"
EXTRAS_PATH = ROOT / "spec" / "extras.json"
HEADER_PATH = ROOT / "src" / "spec_generated.h"
SCRIPT_PATH = ROOT / "linux" / "Medicat_Installer.sh"
BEGIN_MARK = "# BEGIN GENERATED SPEC - edit spec/*.json and run tools/gen_spec.py"
END_MARK = "# END GENERATED SPEC"

HEX32 = re.compile(r"^[0-9a-f]{32}$")
HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
HEX128 = re.compile(r"^[0-9a-f]{128}$")
IDENT = re.compile(r"^[a-z0-9][a-z0-9-]*$")
CATEGORY = re.compile(r"^[A-Za-z0-9_]+$")


def fail(message: str) -> None:
    sys.exit(f"gen_spec: {message}")


def validate(spec: dict, extras: dict) -> None:
    medicat = spec["medicat"]
    archive = medicat["archive"]
    if not HEX32.match(archive["md5"]):
        fail("archive.md5 must be 32 lowercase hex characters")
    if not HEX64.match(archive["sha256"]):
        fail("archive.sha256 must be 64 lowercase hex characters")
    if archive["bytes"] <= 0 or not 50 <= archive["min_bytes_percent"] <= 100:
        fail("archive.bytes / min_bytes_percent out of range")
    parts = medicat["split_archive"]["parts"]
    if len(parts) < 2:
        fail("split_archive needs at least two parts")
    for part in parts:
        if not HEX32.match(part["md5"]) or not HEX40.match(part["sha1"]):
            fail(f"bad checksum on split part {part['file_name']}")
    if len(medicat["mirrors"]) < 2:
        fail("at least two mirrors are required (the Windows GUI has two mirror buttons)")
    for mirror in medicat["mirrors"]:
        if not mirror["url"].startswith("https://"):
            fail(f"mirror {mirror['name']} must use https")
    if not medicat["manifest"]["urls"]:
        fail("manifest.urls is empty")
    updates = spec["updates"]
    if not re.match(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$", updates["github_repository"]):
        fail("updates.github_repository must be owner/name")
    if not updates["checksums_asset"] or "/" in updates["checksums_asset"]:
        fail("updates.checksums_asset must be a plain file name")
    if extras["dest_root"] in ("", ".", "..") or "/" in extras["dest_root"]:
        fail("extras.dest_root must be a single folder name")
    seen: set[str] = set()
    for entry in extras["entries"]:
        ident = entry["id"]
        if not IDENT.match(ident):
            fail(f"extras id {ident!r} must be lowercase letters, digits and dashes")
        if ident in seen:
            fail(f"duplicate extras id {ident}")
        seen.add(ident)
        if not CATEGORY.match(entry["category"]):
            fail(f"{ident}: category must be a plain folder name")
        if entry["type"] not in ("iso", "manual"):
            fail(f"{ident}: type must be iso or manual")
        if not set(entry["targets"]) <= {"linux", "windows"} or not entry["targets"]:
            fail(f"{ident}: targets must be linux and/or windows")
        if not entry["url"].startswith("https://"):
            fail(f"{ident}: url must use https")
        if "/" in entry["file_name"] or "\\" in entry["file_name"]:
            fail(f"{ident}: file_name must not contain a path")
        if entry["type"] == "iso":
            has_sha = "sha256" in entry
            has_sha512 = "sha512" in entry
            has_sha1 = "sha1" in entry
            has_md5 = "md5" in entry
            if not (has_sha or has_sha512 or has_sha1 or has_md5):
                fail(f"{ident}: iso entries need sha256 (preferred), sha512, sha1 or md5")
            if has_sha and not HEX64.match(entry["sha256"]):
                fail(f"{ident}: sha256 must be 64 lowercase hex characters")
            if has_sha512 and not HEX128.match(entry["sha512"]):
                fail(f"{ident}: sha512 must be 128 lowercase hex characters")
            if has_sha1 and not HEX40.match(entry["sha1"]):
                fail(f"{ident}: sha1 must be 40 lowercase hex characters")
            if has_md5 and not HEX32.match(entry["md5"]):
                fail(f"{ident}: md5 must be 32 lowercase hex characters")
            if entry["bytes"] <= 0:
                fail(f"{ident}: bytes must be positive")
            unpack = entry.get("unpack")
            if unpack is not None:
                if unpack.get("format") != "zip" or not unpack.get("member"):
                    fail(f"{ident}: unpack supports only {{format: zip, member: name}}")


def cpp_narrow(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cpp_wide(value: str) -> str:
    if any(ord(ch) > 126 or ord(ch) < 32 for ch in value):
        fail(f"non-ASCII text is not supported in generated C++ strings: {value!r}")
    return "L" + cpp_narrow(value)


def render_header(spec: dict, extras: dict) -> str:
    medicat = spec["medicat"]
    archive = medicat["archive"]
    split = medicat["split_archive"]
    mirrors = medicat["mirrors"]
    alt = medicat["alternative_downloads"]
    links = spec["links"]
    lines: list[str] = []
    out = lines.append
    out("#pragma once")
    out("// Generated by tools/gen_spec.py from spec/medicat.json and spec/extras.json. Do not edit.")
    out("")
    out("#include <cstddef>")
    out("#include <cstdint>")
    out("")
    out("namespace medicat {")
    out("")
    out(f"constexpr int kSpecVersion = {spec['spec_version']};")
    out(f"constexpr wchar_t kMediCatVersion[] = {cpp_wide(medicat['version'])};")
    out(f"constexpr wchar_t kMediCatArchiveFileName[] = {cpp_wide(archive['file_name'])};")
    out(f"constexpr uint64_t kMediCatArchiveFullBytes = {archive['bytes']}ULL;")
    out(f"constexpr uint64_t kMediCatArchiveMinBytes = kMediCatArchiveFullBytes * {archive['min_bytes_percent']} / 100;")
    out(f"constexpr char kMediCatArchiveMd5[] = {cpp_narrow(archive['md5'])};")
    out(f"constexpr char kMediCatArchiveSha256[] = {cpp_narrow(archive['sha256'])};")
    out("")
    out("struct MediCatSplitPart {")
    out("    const wchar_t* fileName;")
    out("    uint64_t fullBytes;")
    out("    const char* md5;   // lowercase hex")
    out("    const char* sha1;  // reference only; installer verifies MD5")
    out("};")
    out("")
    out("constexpr MediCatSplitPart kMediCatSplitParts[] = {")
    for part in split["parts"]:
        out(f"    {{{cpp_wide(part['file_name'])}, {part['bytes']}ULL, {cpp_narrow(part['md5'])},")
        out(f"     {cpp_narrow(part['sha1'])}}},")
    out("};")
    out("constexpr size_t kMediCatSplitPartCount = sizeof(kMediCatSplitParts) / sizeof(kMediCatSplitParts[0]);")
    out(f"constexpr wchar_t kMediCatSplitFirstFileName[] = {cpp_wide(split['parts'][0]['file_name'])};")
    out("")
    out("struct MediCatMirror {")
    out("    const wchar_t* name;")
    out("    const wchar_t* url;")
    out("    bool insecureTls;")
    out("};")
    out("")
    out("constexpr MediCatMirror kMediCatMirrors[] = {")
    for mirror in mirrors:
        flag = "true" if mirror.get("insecure_tls") else "false"
        out(f"    {{{cpp_wide(mirror['name'])}, {cpp_wide(mirror['url'])}, {flag}}},")
    out("};")
    out("constexpr size_t kMediCatMirrorCount = sizeof(kMediCatMirrors) / sizeof(kMediCatMirrors[0]);")
    out(f"constexpr wchar_t kDownloadMirror1Url[] = {cpp_wide(mirrors[0]['url'])};")
    out(f"constexpr wchar_t kDownloadMirror2Url[] = {cpp_wide(mirrors[1]['url'])};")
    out("")
    out(f"constexpr wchar_t kDownloadTorrentUrl[] = {cpp_wide(medicat['torrent']['url'])};")
    out(f"constexpr wchar_t kDownloadMagnetUrl[] = {cpp_wide(medicat['torrent']['magnet'])};")
    out(f"constexpr wchar_t kDownloadGoogleDriveUrl[] = {cpp_wide(alt['google_drive'])};")
    out(f"constexpr wchar_t kDownloadMegaUrl[] = {cpp_wide(alt['mega'])};")
    out(f"constexpr wchar_t kDownloadAllUrl[] = {cpp_wide(alt['all'])};")
    out(f"constexpr wchar_t kManualInstallDocUrl[] = {cpp_wide(links['manual_install_doc'])};")
    out(f"constexpr wchar_t kBetaFeedbackUrl[] = {cpp_wide(links['issues'])};")
    out(f"constexpr wchar_t kDiscordSupportUrl[] = {cpp_wide(links['discord'])};")
    out(f"constexpr wchar_t kSevenZipProjectUrl[] = {cpp_wide(links['seven_zip'])};")
    out(f"constexpr wchar_t kAria2ProjectUrl[] = {cpp_wide(links['aria2'])};")
    out(f"constexpr wchar_t kVentoyProjectUrl[] = {cpp_wide(links['ventoy'])};")
    out("")
    manifest = medicat["manifest"]
    out(f"constexpr wchar_t kMd5ManifestFileName[] = {cpp_wide(manifest['file_name'])};")
    out("constexpr const wchar_t* kMd5ManifestUrls[] = {")
    for url in manifest["urls"]:
        out(f"    {cpp_wide(url)},")
    out("};")
    out("constexpr size_t kMd5ManifestUrlCount = sizeof(kMd5ManifestUrls) / sizeof(kMd5ManifestUrls[0]);")
    out(f"constexpr uint32_t kMediCatManifestFileCount = {manifest['file_count']}U;")
    out(f"constexpr uint64_t kMediCatExtractedBytes = {manifest['extracted_bytes']}ULL;")
    out("")
    usb = spec["usb"]
    out(f"constexpr uint64_t kSpecMinDriveCapacityBytes = {usb['min_capacity_bytes']}ULL;")
    out(f"constexpr uint64_t kSpecRecommendedDriveCapacityBytes = {usb['recommended_capacity_bytes']}ULL;")
    out(f"constexpr wchar_t kSpecDataPartitionLabel[] = {cpp_wide(usb['data_partition_label'])};")
    ventoy = spec["ventoy"]
    out(f"constexpr wchar_t kVentoyKnownGoodVersion[] = {cpp_wide(ventoy['known_good_version'])};")
    pinned = ventoy.get("pinned_version") or ""
    out(f"constexpr wchar_t kVentoyPinnedVersion[] = {cpp_wide(pinned)};  // empty = latest")
    out(f"constexpr bool kVentoyDefaultSecureBoot = {'true' if ventoy['secure_boot'] else 'false'};")
    out(f"constexpr bool kVentoyDefaultGpt = {'true' if ventoy['default_partition_style'] == 'gpt' else 'false'};")
    updates = spec["updates"]
    out(f"constexpr wchar_t kUpdateRepository[] = {cpp_wide(updates['github_repository'])};  // owner/name on GitHub")
    out(f"constexpr wchar_t kUpdateChecksumsAssetName[] = {cpp_wide(updates['checksums_asset'])};")
    out("")
    out("struct MediCatExtra {")
    out("    const wchar_t* id;")
    out("    const wchar_t* name;")
    out("    const wchar_t* version;")
    out("    const wchar_t* category;   // folder under kExtrasDestRoot")
    out("    const wchar_t* targets;    // comma separated: linux,windows")
    out("    const wchar_t* type;       // iso | manual")
    out("    const wchar_t* url;")
    out("    const wchar_t* fileName;")
    out("    uint64_t bytes;")
    out("    const char* sha256;        // empty when the project publishes another digest")
    out("    const char* sha512;")
    out("    const char* sha1;")
    out("    const char* md5;")
    out("    const wchar_t* unpackFormat;  // empty | zip")
    out("    const wchar_t* unpackMember;")
    out("    const wchar_t* homepage;")
    out("    const wchar_t* license;")
    out("    const wchar_t* description;")
    out("};")
    out("")
    out(f"constexpr wchar_t kExtrasCatalogVersion[] = {cpp_wide(extras['catalog_version'])};")
    out(f"constexpr wchar_t kExtrasDestRoot[] = {cpp_wide(extras['dest_root'])};")
    out("constexpr MediCatExtra kMediCatExtras[] = {")
    for entry in extras["entries"]:
        unpack = entry.get("unpack") or {}
        out("    {")
        out(f"        {cpp_wide(entry['id'])}, {cpp_wide(entry['name'])}, {cpp_wide(entry['version'])},")
        out(f"        {cpp_wide(entry['category'])}, {cpp_wide(','.join(entry['targets']))}, {cpp_wide(entry['type'])},")
        out(f"        {cpp_wide(entry['url'])},")
        out(f"        {cpp_wide(entry['file_name'])}, {entry['bytes']}ULL,")
        out(f"        {cpp_narrow(entry.get('sha256', ''))}, {cpp_narrow(entry.get('sha512', ''))},")
        out(f"        {cpp_narrow(entry.get('sha1', ''))}, {cpp_narrow(entry.get('md5', ''))},")
        out(f"        {cpp_wide(unpack.get('format', ''))}, {cpp_wide(unpack.get('member', ''))},")
        out(f"        {cpp_wide(entry['homepage'])}, {cpp_wide(entry['license'])},")
        out(f"        {cpp_wide(entry['description'])},")
        out("    },")
    out("};")
    out("constexpr size_t kMediCatExtraCount = sizeof(kMediCatExtras) / sizeof(kMediCatExtras[0]);")
    out("")
    out("}  // namespace medicat")
    return "\n".join(lines) + "\n"


def bash_quote(value: str) -> str:
    return "'" + str(value).replace("'", "'\\''") + "'"


def bash_array(name: str, values: list) -> str:
    return f"{name}=({' '.join(bash_quote(v) for v in values)})"


def render_bash_block(spec: dict, extras: dict) -> str:
    medicat = spec["medicat"]
    archive = medicat["archive"]
    split = medicat["split_archive"]
    mirrors = medicat["mirrors"]
    manifest = medicat["manifest"]
    usb = spec["usb"]
    free = spec["free_space"]
    ventoy = spec["ventoy"]
    links = spec["links"]
    entries = extras["entries"]
    updates = spec["updates"]
    body: list[str] = []
    out = body.append
    out(f"SpecVersion={spec['spec_version']}")
    out(f"MedicatVersion={bash_quote(medicat['version'])}")
    out(f"Medicat7zFile={bash_quote(archive['file_name'])}")
    out(f"Medicat7zBytes={archive['bytes']}")
    out(f"Medicat7zMinBytes={archive['bytes'] * archive['min_bytes_percent'] // 100}")
    out(f"Medicat7zMd5={bash_quote(archive['md5'])}")
    out(f"Medicat256Hash={bash_quote(archive['sha256'])}")
    out(f"Medicat7zTorrentSubdir={bash_quote(archive['torrent_subdir'])}")
    out(f"MedicatSplitBase={bash_quote(split['base_name'])}")
    out(bash_array("MedicatSplitFiles", [p["file_name"] for p in split["parts"]]))
    out(bash_array("MedicatSplitSizes", [p["bytes"] for p in split["parts"]]))
    out(bash_array("MedicatSplitMd5s", [p["md5"] for p in split["parts"]]))
    out(bash_array("MedicatMirrorNames", [m["name"] for m in mirrors]))
    out(bash_array("MedicatMirrorUrls", [m["url"] for m in mirrors]))
    out(bash_array("MedicatMirrorInsecure", ["true" if m.get("insecure_tls") else "false" for m in mirrors]))
    out(f"MedicatTorrentUrl={bash_quote(medicat['torrent']['url'])}")
    out(f"MedicatMagnetUrl={bash_quote(medicat['torrent']['magnet'])}")
    out(f"MedicatManifestFile={bash_quote(manifest['file_name'])}")
    out(bash_array("MedicatManifestUrls", manifest["urls"]))
    out(f"MedicatManifestFileCount={manifest['file_count']}")
    out(f"MedicatExtractedBytes={manifest['extracted_bytes']}")
    out(f"MedicatUsbMinBytes={usb['min_capacity_bytes']}")
    out(f"MedicatUsbRecommendedBytes={usb['recommended_capacity_bytes']}")
    out(f"MedicatDataLabel={bash_quote(usb['data_partition_label'])}")
    out(f"MedicatDataFs={bash_quote(usb['filesystem'])}")
    out(f"MedicatDownloadMinFreeBytes={free['download_bytes']}")
    out(f"MedicatWorkMinFreeBytes={free['work_bytes']}")
    out(f"MedicatUsbMinFreeBytes={free['usb_extract_bytes']}")
    out(f"VentoyKnownGoodVersion={bash_quote(ventoy['known_good_version'])}")
    out(f"VentoyPinnedVersion={bash_quote(ventoy.get('pinned_version') or '')}")
    out(f"VentoyDefaultPartitionStyle={bash_quote(ventoy['default_partition_style'])}")
    out(f"VentoyDefaultSecureBoot={bash_quote('true' if ventoy['secure_boot'] else 'false')}")
    out(f"VentoyReleaseApi={bash_quote(ventoy['release_api'])}")
    out(f"VentoyLinuxTarUrlTemplate={bash_quote(ventoy['linux_tarball_url_template'])}")
    out(f"LinkManualInstallDoc={bash_quote(links['manual_install_doc'])}")
    out(f"LinkIssues={bash_quote(links['issues'])}")
    out(f"LinkDiscord={bash_quote(links['discord'])}")
    out(f"UpdateRepository={bash_quote(updates['github_repository'])}")
    out(f"UpdateChecksumsAsset={bash_quote(updates['checksums_asset'])}")
    out(f"ExtrasCatalogVersion={bash_quote(extras['catalog_version'])}")
    out(f"ExtrasDestRoot={bash_quote(extras['dest_root'])}")
    out(bash_array("ExtrasIds", [e["id"] for e in entries]))
    out(bash_array("ExtrasNames", [e["name"] for e in entries]))
    out(bash_array("ExtrasVersions", [e["version"] for e in entries]))
    out(bash_array("ExtrasCategories", [e["category"] for e in entries]))
    out(bash_array("ExtrasTargets", [",".join(e["targets"]) for e in entries]))
    out(bash_array("ExtrasTypes", [e["type"] for e in entries]))
    out(bash_array("ExtrasUrls", [e["url"] for e in entries]))
    out(bash_array("ExtrasFileNames", [e["file_name"] for e in entries]))
    out(bash_array("ExtrasBytes", [e["bytes"] for e in entries]))
    out(bash_array("ExtrasSha256", [e.get("sha256", "") for e in entries]))
    out(bash_array("ExtrasSha512", [e.get("sha512", "") for e in entries]))
    out(bash_array("ExtrasSha1", [e.get("sha1", "") for e in entries]))
    out(bash_array("ExtrasMd5", [e.get("md5", "") for e in entries]))
    out(bash_array("ExtrasUnpackFormat", [(e.get("unpack") or {}).get("format", "") for e in entries]))
    out(bash_array("ExtrasUnpackMember", [(e.get("unpack") or {}).get("member", "") for e in entries]))
    out(bash_array("ExtrasHomepages", [e["homepage"] for e in entries]))
    out(bash_array("ExtrasLicenses", [e["license"] for e in entries]))
    out(bash_array("ExtrasDescriptions", [e["description"] for e in entries]))
    lines = [
        BEGIN_MARK,
        "# shellcheck disable=SC2034  # every spec value is defined here; the script uses only some of them",
        "function loadSpec() {",
    ]
    lines.extend("\t" + line for line in body)
    lines.append("}")
    lines.append(END_MARK)
    return "\n".join(lines) + "\n"


def splice_script(script_text: str, block: str) -> str:
    begin = script_text.find(BEGIN_MARK)
    end = script_text.find(END_MARK)
    if begin < 0 or end < 0 or end < begin:
        fail(f"{SCRIPT_PATH} is missing the GENERATED SPEC markers")
    end += len(END_MARK) + 1  # include the newline after the end marker
    return script_text[:begin] + block + script_text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the generated outputs are stale")
    args = parser.parse_args()

    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    extras = json.loads(EXTRAS_PATH.read_text(encoding="utf-8"))
    validate(spec, extras)

    header = render_header(spec, extras)
    script_old = SCRIPT_PATH.read_text(encoding="utf-8")
    script_new = splice_script(script_old, render_bash_block(spec, extras))
    header_old = HEADER_PATH.read_text(encoding="utf-8") if HEADER_PATH.exists() else ""

    stale = []
    if header_old != header:
        stale.append(str(HEADER_PATH.relative_to(ROOT)))
    if script_old != script_new:
        stale.append(str(SCRIPT_PATH.relative_to(ROOT)))

    if args.check:
        if stale:
            print("gen_spec: stale generated output, run tools/gen_spec.py: " + ", ".join(stale))
            return 1
        print("gen_spec: generated outputs are up to date")
        return 0

    HEADER_PATH.write_text(header, encoding="utf-8", newline="\n")
    SCRIPT_PATH.write_text(script_new, encoding="utf-8", newline="\n")
    print("gen_spec: wrote " + ", ".join(str(p.relative_to(ROOT)) for p in (HEADER_PATH, SCRIPT_PATH)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
