#pragma once
// Generated by tools/gen_spec.py from spec/medicat.json and spec/extras.json. Do not edit.

#include <cstddef>
#include <cstdint>

namespace medicat {

constexpr int kSpecVersion = 1;
constexpr wchar_t kMediCatVersion[] = L"v21.12";
constexpr wchar_t kMediCatArchiveFileName[] = L"MediCat.USB.v21.12.7z";
constexpr uint64_t kMediCatArchiveFullBytes = 22994783619ULL;
constexpr uint64_t kMediCatArchiveMinBytes = kMediCatArchiveFullBytes * 95 / 100;
constexpr char kMediCatArchiveMd5[] = "db50f96a5c7b5ec6dc9ed77ea29fffb0";
constexpr char kMediCatArchiveSha256[] = "a306331453897d2b20644ca9334bb0015b126b8647cecec8d9b2d300a0027ea4";

struct MediCatSplitPart {
    const wchar_t* fileName;
    uint64_t fullBytes;
    const char* md5;   // lowercase hex
    const char* sha1;  // reference only; installer verifies MD5
};

constexpr MediCatSplitPart kMediCatSplitParts[] = {
    {L"MediCat.USB.v21.12.zip.001", 4290772992ULL, "277793dcf0e31736f0790162a89d07c9",
     "ef13910a43c1ae9d04a86b2853f11e44cf7ae193"},
    {L"MediCat.USB.v21.12.zip.002", 4290772992ULL, "a4700261f32d4df5092c5dd5ea6aaa2d",
     "6106453ea19646a889864328758886c3726c96f2"},
    {L"MediCat.USB.v21.12.zip.003", 4290772992ULL, "6b523273c5c7ed1ddc5920dec95b8509",
     "69a5c48bdba8fe7ae33b9d251813230f2868d731"},
    {L"MediCat.USB.v21.12.zip.004", 4290772992ULL, "35fac6ff4902d62e6e5fd2dab1050a3f",
     "ba7d0aa2f55bc9c96bad3d47f762d1dd324fc021"},
    {L"MediCat.USB.v21.12.zip.005", 4290772992ULL, "7f416a7d9ff0051ae75bbf44a411b8e4",
     "543803780e5fc6a0f3de05791b1b48d371d23215"},
    {L"MediCat.USB.v21.12.zip.006", 2917026620ULL, "32d84a280af91ae408f55a7722ee6818",
     "de48d627bc9baaff7646357e87f4a6cd7f6bb450"},
};
constexpr size_t kMediCatSplitPartCount = sizeof(kMediCatSplitParts) / sizeof(kMediCatSplitParts[0]);
constexpr wchar_t kMediCatSplitFirstFileName[] = L"MediCat.USB.v21.12.zip.001";

struct MediCatMirror {
    const wchar_t* name;
    const wchar_t* url;
    bool insecureTls;
};

constexpr MediCatMirror kMediCatMirrors[] = {
    {L"files.medicatusb.com", L"https://files.medicatusb.com/files/v21.12/MediCat.USB.v21.12.7z", false},
    {L"files.dog", L"https://files.dog/OD%20Rips/MediCat/v21.12/MediCat.USB.v21.12.7z", false},
};
constexpr size_t kMediCatMirrorCount = sizeof(kMediCatMirrors) / sizeof(kMediCatMirrors[0]);
constexpr wchar_t kDownloadMirror1Url[] = L"https://files.medicatusb.com/files/v21.12/MediCat.USB.v21.12.7z";
constexpr wchar_t kDownloadMirror2Url[] = L"https://files.dog/OD%20Rips/MediCat/v21.12/MediCat.USB.v21.12.7z";

constexpr wchar_t kDownloadTorrentUrl[] = L"https://raw.githubusercontent.com/26zl/medicat_installer/main/spec/MediCat_USB_v21.12.torrent";
constexpr wchar_t kDownloadMagnetUrl[] = L"magnet:?xt=urn:btih:1D714BDF37890669E98933B724B55D47E7F2D01B";
constexpr wchar_t kDownloadGoogleDriveUrl[] = L"https://drive.google.com/drive/folders/0B80MkZEQZejCSDZsY2NKbVJNWjg?resourcekey=0-wMGHCpg8SwR13oOYDfjPuA";
constexpr wchar_t kDownloadMegaUrl[] = L"https://mega.nz/folder/jg1DWbaK#Qo6XsYzjx-HyIpxj8xQTiQ";
constexpr wchar_t kDownloadAllUrl[] = L"http://medicatusb.com/#downloads";
constexpr wchar_t kManualInstallDocUrl[] = L"https://medicatusb.com/docs/medicat/installation/manual-install/";
constexpr wchar_t kBetaFeedbackUrl[] = L"https://github.com/26zl/medicat_installer/issues";
constexpr wchar_t kDiscordSupportUrl[] = L"https://url.medicatusb.com/discord";
constexpr wchar_t kSevenZipProjectUrl[] = L"https://www.7-zip.org/";
constexpr wchar_t kAria2ProjectUrl[] = L"https://aria2.github.io/";
constexpr wchar_t kVentoyProjectUrl[] = L"https://www.ventoy.net/en/index.html";

constexpr wchar_t kMd5ManifestFileName[] = L"MedicatFiles.md5";
constexpr const wchar_t* kMd5ManifestUrls[] = {
    L"https://raw.githubusercontent.com/26zl/medicat_installer/main/MedicatFiles.md5",
    L"https://raw.githubusercontent.com/mon5termatt/medicat_installer/main/MedicatFiles.md5",
};
constexpr size_t kMd5ManifestUrlCount = sizeof(kMd5ManifestUrls) / sizeof(kMd5ManifestUrls[0]);
constexpr uint32_t kMediCatManifestFileCount = 29652U;
constexpr uint64_t kMediCatExtractedBytes = 28311000111ULL;

constexpr uint64_t kSpecMinDriveCapacityBytes = 30064771072ULL;
constexpr uint64_t kSpecRecommendedDriveCapacityBytes = 64000000000ULL;
constexpr wchar_t kSpecDataPartitionLabel[] = L"Medicat";
constexpr wchar_t kVentoyKnownGoodVersion[] = L"1.1.17";
constexpr wchar_t kVentoyPinnedVersion[] = L"";  // empty = latest
constexpr bool kVentoyDefaultSecureBoot = true;
constexpr bool kVentoyDefaultGpt = false;
constexpr wchar_t kUpdateRepository[] = L"26zl/medicat_installer";  // owner/name on GitHub
constexpr wchar_t kUpdateChecksumsAssetName[] = L"SHA256SUMS.txt";

struct MediCatExtra {
    const wchar_t* id;
    const wchar_t* name;
    const wchar_t* version;
    const wchar_t* category;   // folder under kExtrasDestRoot
    const wchar_t* targets;    // comma separated: linux,windows
    const wchar_t* type;       // iso | manual
    const wchar_t* url;
    const wchar_t* fileName;
    uint64_t bytes;
    const char* sha256;        // empty when the project publishes another digest
    const char* sha512;
    const char* sha1;
    const char* md5;
    const wchar_t* unpackFormat;  // empty | zip
    const wchar_t* unpackMember;
    const wchar_t* homepage;
    const wchar_t* license;
    const wchar_t* description;
};

constexpr wchar_t kExtrasCatalogVersion[] = L"2026-09-27";
constexpr wchar_t kExtrasDestRoot[] = L"Extras";
constexpr MediCatExtra kMediCatExtras[] = {
    {
        L"systemrescue", L"SystemRescue", L"13.02",
        L"Rescue", L"linux,windows", L"iso",
        L"https://fastly-cdn.system-rescue.org/releases/13.02/systemrescue-13.02-amd64.iso",
        L"systemrescue-13.02-amd64.iso", 1381629952ULL,
        "ad4d670b72859d887c7960142a9a9d36a3e50446694a035e254442f65d6e7572", "",
        "", "",
        L"", L"",
        L"https://www.system-rescue.org/", L"GPL-2.0-or-later (Arch-based live system, mixed licenses)",
        L"Arch-based rescue system with disk, network and recovery tools for Linux and Windows machines.",
    },
    {
        L"gparted-live", L"GParted Live", L"1.8.1-6",
        L"Partition_and_Imaging", L"linux,windows", L"iso",
        L"https://downloads.sourceforge.net/gparted/gparted-live-1.8.1-6-amd64.iso",
        L"gparted-live-1.8.1-6-amd64.iso", 720371712ULL,
        "d789c38779f0d6f7026c12f44c2c52a04f66e28a1aea7d51f3045ad1bbf28411", "",
        "", "",
        L"", L"",
        L"https://gparted.org/", L"GPL-2.0-or-later",
        L"Resize, move, copy and check partitions (NTFS, ext4, exFAT, FAT, btrfs and more).",
    },
    {
        L"clonezilla-live", L"Clonezilla Live", L"3.1.2-9",
        L"Partition_and_Imaging", L"linux,windows", L"iso",
        L"https://downloads.sourceforge.net/project/clonezilla/clonezilla_live_stable/3.1.2-9/clonezilla-live-3.1.2-9-amd64.iso",
        L"clonezilla-live-3.1.2-9-amd64.iso", 437256192ULL,
        "", "",
        "", "99353cf50559fe8e5450643a764f0f57",
        L"", L"",
        L"https://clonezilla.org/", L"GPL-2.0",
        L"Disk and partition imaging and cloning, sector-level or filesystem-aware.",
    },
    {
        L"rescuezilla", L"Rescuezilla", L"2.6.2",
        L"Partition_and_Imaging", L"linux,windows", L"iso",
        L"https://github.com/rescuezilla/rescuezilla/releases/download/2.6.2/rescuezilla-2.6.2-64bit.noble.iso",
        L"rescuezilla-2.6.2-64bit.noble.iso", 1594339328ULL,
        "285db0af83213e2297490ca1cfd74ecd607c3b0a2f1d14e11a8412c0b71eea50", "",
        "", "",
        L"", L"",
        L"https://rescuezilla.com/", L"GPL-3.0",
        L"Point-and-click backup and restore, compatible with Clonezilla images.",
    },
    {
        L"memtest86plus", L"Memtest86+", L"8.10",
        L"Diagnostics", L"linux,windows", L"iso",
        L"https://www.memtest.org/download/v8.10/mt86plus_8.10_x86_64.iso.zip",
        L"mt86plus_8.10_x86_64.iso", 233712ULL,
        "93530005d6ac6a85aa2a49c68604a43c25794ecccf796c4f8849a73a8001be9a", "",
        "", "",
        L"zip", L"memtest.iso",
        L"https://www.memtest.org/", L"GPL-2.0",
        L"Stand-alone RAM tester for BIOS and UEFI machines.",
    },
    {
        L"hirens-bootcd-pe", L"Hiren's BootCD PE", L"1.0.8",
        L"Windows_Rescue", L"windows", L"iso",
        L"https://www.hirensbootcd.org/files/HBCD_PE_x64.iso",
        L"HBCD_PE_x64.iso", 3291686912ULL,
        "8c4c670c9c84d6c4b5a9c32e0aa5a55d8c23de851d259207d54679ea774c2498", "",
        "", "",
        L"", L"",
        L"https://www.hirensbootcd.org/", L"Freeware; bundled tools keep their own licenses",
        L"Windows 11 PE based repair environment with password, driver, backup and diagnostics tools.",
    },
    {
        L"ubuntu-desktop-lts", L"Ubuntu Desktop LTS", L"24.04.5.1",
        L"Live_Linux", L"linux", L"iso",
        L"https://releases.ubuntu.com/24.04/ubuntu-24.04.5.1-desktop-amd64.iso",
        L"ubuntu-24.04.5.1-desktop-amd64.iso", 6250332160ULL,
        "4da4a0c9035da8e68a59a838674f403f0a54472c78a83b4fb7f78d03588f85a7", "",
        "", "",
        L"", L"",
        L"https://ubuntu.com/download/desktop", L"Mixed open source",
        L"Live desktop and installer; handy for rescuing files from a Linux or Windows disk with a full GUI.",
    },
    {
        L"windows-11-iso", L"Windows 11 installation media", L"current",
        L"Windows_Install", L"windows", L"manual",
        L"https://www.microsoft.com/software-download/windows11",
        L"Win11.iso", 0ULL,
        "", "",
        "", "",
        L"", L"",
        L"https://www.microsoft.com/software-download/windows11", L"Proprietary (Microsoft); download from Microsoft only",
        L"Microsoft issues time-limited download links, so fetch the ISO from the Microsoft page and copy it into Extras/Windows_Install/ on the stick.",
    },
    {
        L"linux-mint-cinnamon", L"Linux Mint Cinnamon", L"22.3",
        L"Live_Linux", L"linux", L"iso",
        L"https://mirrors.edge.kernel.org/linuxmint/stable/22.3/linuxmint-22.3-cinnamon-64bit.iso",
        L"linuxmint-22.3-cinnamon-64bit.iso", 3091660800ULL,
        "a081ab202cfda17f6924128dbd2de8b63518ac0531bcfe3f1a1b88097c459bd4", "",
        "", "",
        L"", L"",
        L"https://linuxmint.com/", L"Mixed open source",
        L"Beginner-friendly live desktop and installer; the usual choice when a Windows PC is being moved to Linux.",
    },
    {
        L"debian-live-kde", L"Debian Live KDE", L"13.7.0",
        L"Live_Linux", L"linux", L"iso",
        L"https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-13.7.0-amd64-kde.iso",
        L"debian-live-13.7.0-amd64-kde.iso", 4186112000ULL,
        "37dedc921f50325665c75829597126b3eeb70ff5cd8c511a7230ace09ae939be", "",
        "", "",
        L"", L"",
        L"https://www.debian.org/CD/live/", L"Mixed open source (DFSG)",
        L"Debian stable live desktop with the Calamares installer. The current-live URL moves at each point release, so bump the version when it 404s.",
    },
    {
        L"shredos", L"ShredOS (nwipe)", L"2025.11 / nwipe 0.42",
        L"Disk_Wipe", L"linux,windows", L"iso",
        L"https://github.com/PartialVolume/shredos.x86_64/releases/download/v2025.11_31_x86-64_0.42/shredos-2025.11_31_x86-64_v0.42_20260716.iso",
        L"shredos-2025.11_31_x86-64_v0.42_20260716.iso", 360710144ULL,
        "", "",
        "ef4b41f95f96b2bc80ee3fbe2e9ca9ea51750569", "",
        L"", L"",
        L"https://github.com/PartialVolume/shredos.x86_64", L"GPL-2.0",
        L"Boots straight into nwipe to securely erase disks (DoD, PRNG, verify) before a machine is sold or recycled. The project publishes SHA-1 only.",
    },
    {
        L"windows-10-iso", L"Windows 10 installation media", L"22H2",
        L"Windows_Install", L"windows", L"manual",
        L"https://www.microsoft.com/software-download/windows10ISO",
        L"Win10_22H2.iso", 0ULL,
        "", "",
        "", "",
        L"", L"",
        L"https://www.microsoft.com/software-download/windows10ISO", L"Proprietary (Microsoft); download from Microsoft only",
        L"Still needed for machines that cannot run Windows 11. Microsoft issues time-limited links, so fetch the ISO from the Microsoft page and copy it into Extras/Windows_Install/ on the stick.",
    },
    {
        L"caine", L"CAINE", L"14.0",
        L"Forensics", L"linux,windows", L"iso",
        L"https://www.caine-live.net/Downloads/caine14.0.iso",
        L"caine14.0.iso", 4169138176ULL,
        "2702226cf9ee131ee54e9649d6d90008f3fe851ba35939f43ae8cb614a00d564", "",
        "", "",
        L"", L"",
        L"https://www.caine-live.net/", L"GPL-3.0 (Ubuntu-based live system, mixed licenses)",
        L"Computer Aided INvestigative Environment: boots with all disks read-only, with Autopsy, Guymager, PhotoRec and other acquisition and analysis tools. For authorized investigations and data recovery.",
    },
    {
        L"parrot-security", L"Parrot Security", L"7.3",
        L"Forensics", L"linux,windows", L"iso",
        L"https://deb.parrot.sh/parrot/iso/7.3/Parrot-security-7.3_amd64.iso",
        L"Parrot-security-7.3_amd64.iso", 8555526144ULL,
        "fe8ec64f92d8d629b1fcae85d9fab81c87e3ff30584201e82b7c453a740cefbc", "",
        "", "",
        L"", L"",
        L"https://www.parrotsec.org/", L"GPL-3.0 (Debian-based, mixed licenses)",
        L"Security and forensics live system with a dedicated forensic boot mode (no automount, no swap) plus the usual pentest and analysis toolset. Large image.",
    },
    {
        L"sift-workstation", L"SANS SIFT Workstation", L"current",
        L"Forensics", L"linux,windows", L"manual",
        L"https://www.sans.org/tools/sift-workstation/",
        L"SIFT-Workstation.ova", 0ULL,
        "", "",
        "", "",
        L"", L"",
        L"https://www.sans.org/tools/sift-workstation/", L"Free for use; download requires a SANS account",
        L"DFIR toolkit (Plaso, Volatility, Sleuth Kit and more). SANS only offers it behind a login as a VM image or an Ubuntu install script, so fetch it from the SANS page; it is not a bootable ISO.",
    },
    {
        L"paladin", L"SUMURI PALADIN", L"current",
        L"Forensics", L"linux,windows", L"manual",
        L"https://sumuri.com/paladin/",
        L"paladin.iso", 0ULL,
        "", "",
        "", "",
        L"", L"",
        L"https://sumuri.com/paladin/", L"Free edition; download requires registration",
        L"Forensic boot ISO with a write-blocked imager and disk tools. SUMURI issues the download after registration, so fetch it from their page and copy the ISO into Extras/Forensics/.",
    },
    {
        L"tsurugi-acquire", L"Tsurugi Acquire", L"2021.1",
        L"Forensics", L"linux,windows", L"iso",
        L"https://ftp.nluug.nl/os/Linux/distr/tsurugi/02.Tsurugi_Acquire/tsurugi_acquire_2021.1.iso",
        L"tsurugi_acquire_2021.1.iso", 1215299584ULL,
        "", "bd5488e9e75bbcbc6560d166031e84c70bf19c1b9db6f872df99212fef110296c3e7735e39bdee533aaaa92a64e1096fb674b1d45dd4c88cde280442737d77fe",
        "", "",
        L"", L"",
        L"https://tsurugi-linux.org/", L"Free to use (Ubuntu-based, mixed licenses)",
        L"Small Tsurugi image built for evidence acquisition: boots read-only and images disks with Guymager, dc3dd and ewfacquire. The project publishes SHA-512 only.",
    },
    {
        L"tsurugi-linux", L"Tsurugi Linux LAB", L"26.03",
        L"Forensics", L"linux,windows", L"iso",
        L"https://mirrors.gandi.net/tsurugi/01.Tsurugi_Linux_%5BLAB%5D/tsurugi_linux_26.03.iso",
        L"tsurugi_linux_26.03.iso", 11786315776ULL,
        "", "1284c3b4145ef2201e831350fde20a1445171be66ca34ab909cbd22eb77d5f19ec28a26275955538bddf7abb77ec5ac0c05f3383502c2ac83770150be1c31d8c",
        "", "",
        L"", L"",
        L"https://tsurugi-linux.org/", L"Free to use (Ubuntu-based, mixed licenses)",
        L"Full DFIR lab live system (memory, disk, network and malware analysis, OSINT). Very large image; Tsurugi Acquire covers the acquisition part alone.",
    },
};
constexpr size_t kMediCatExtraCount = sizeof(kMediCatExtras) / sizeof(kMediCatExtras[0]);

}  // namespace medicat
